GCP Service Account Credential as docker env variable for cloud scanner
deepfence/cloud-scanner pull request #32
Opened 2024-10-09 17:03 UTC by shyam0904a

[+] Added support for passing in Service Account Key Credential content as base64 encoded env variable.
[+] Does this break anything : No, All existing functionality works.

```
data "google_client_config" "current" {}

resource "google_project_service" "cloud_resource_manager" {
  project = ""
  service = "cloudresourcemanager.googleapis.com"
  disable_on_destroy = false
}

module "cloud_scanner_example_multiple_project" {
  source                   = "deepfence/cloud-scanner/gcp//examples/gce-vm"
  version                  = "0.8.0"
  # gcp service account name
  name                     = "deepfence-cloud-scanner"
  # project_id example: dev1-123456
  project_id               = ""
  # org mode for multiple projects
  isOrganizationDeployment = true
}

resource "google_service_account_key" "cloud_scanner_key" {
  service_account_id = module.cloud_scanner_example_multiple_project.service_account_email
}

output "service_account_email" {
  value = module.cloud_scanner_example_multiple_project.service_account_email
}

output "service_account_key" {
  value     = google_service_account_key.cloud_scanner_key.private_key
  sensitive = true
}

```

2024-10-09 17:16 UTC, ramanan-ravi requested changes

2024-10-09 17:16 UTC, ramanan-ravi commented on service/service.go
> +    configDir := "/home/deepfence/.config/gcloud/"
```
configDir := util.HomeDirectory+"/.config/gcloud/"
```

2024-10-09 17:27 UTC, shyam0904a commented on service/service.go
> +    configDir := "/home/deepfence/.config/gcloud/"
Resolved

2024-10-10 18:16 UTC, ramanan-ravi approved these changes

2024-10-10 18:17 UTC, merged